name: realm-update-reminder
on:
  pull_request: ## should be on pull request
    branches:
      - master
      - staging
    # paths:
    #   - 'learning.swift'

jobs:
  build:

    name: remind

    runs-on: ubuntu-latest

    steps:
      - name: Run a command here
      env:
        GIT_DIFF: ${{ git diff --unified=0 -S'print(' learning.swift }}
        GIT_DIFF_ECH: ${{ echo git diff --unified=0 -S'print(' learning.swift }}
      run: |
        echo thediff "$GIT_DIFF"
        echo thediff_E "$GIT_DIFF_ECH"
      - name: Check if diff was nil
      if: $GIT_DIFF == ''
      run: echo git_dif was nil

