name: realm-update-reminder
on:
  pull_request:
    branches:
      - master
      - staging
    paths:
      - 'learning.swift'

jobs:
  build:

    name: remind

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout @v1
        run: echo checked out
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Prepare repo
        env:
          GIT_MASTER_BRANCH_SHA: ${{ github.event.pull_request.base.sha }}
          GIT_COMMIT_SHA: ${{ github.event.after }}
          GIT_TOKEN: ${{ github.token }}
        run: |
          echo "${GITHUB_REF:11}"
          echo "current commit sha: $GIT_COMMIT_SHA"
          git checkout test-work
          git checkout master
          git checkout test-work
          #echo $(git branch)
          echo "master branch base sha is $GIT_MASTER_BRANCH_SHA"
          echo "newline to trigger the bot"
          echo $(git log -n5 --pretty=oneline)
      - name: Search for modified lines beginning with print here
        run: |
          echo Starting multiline
          search=$(git diff 4ce19158ecac5ddeff87e87ee406fce820f823a2 --unified=0 -G'Realm.configureRealm\(schemaVersion:' learning.swift | egrep '[+-]Realm.configureRealm\(schemaVersion:')
          before=$(echo $search | grep + | egrep -o [0-9]+)
          #after=$(echo $search | grep - | egrep -o [0-9]+)
          if [ ! -z "$search" ]
          then
            echo "We modified the line in this file make sure its correct"
            echo "Good!"
            echo "$search"
            exit 0
          else 
            echo "failure"
            exit 1
          fi
        shell: bash