name: realm-update-reminder
on:
  pull_request:
    branches:
      - master
      - staging
    paths:
      - 'learning.swift'

jobs:
  build:

    name: remind

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Search for modified lines beginning with "print" here
        run: |
          search=$(git diff --unified=0 -G'print' learning.swift)
          if [ ! -z "$search" ]; then
            echo "We modified the line in this file make sure its correct"
          fi
          echo Done!
        shell: bash