name: realm-update-reminder
on:
  push: ## should be on pull request
    branches:
      - master
      - staging
    # paths:
    #   - 'learning.swift'

jobs:
  build:

    name: remind

    runs-on: ubuntu-latest

    steps:
      - name: Run a command here
        run: |
          echo git diff --unified=0 -S'print(' learning.swift
          echo Done!

